### ISSUE TITLE
merge anykernel 3 from osmosis

### ISSUE THREAD

**Issue by improbir** [uditkarode/crimson#1]
https://github.com/osm0sis/AnyKernel3

for better CPU idling and enhance performance.

**Comment by uditkarode** [comment]
why merge it into the kernel tree

**Comment by improbir** [comment]
we use for our device for better cpu idling and enhance device performance and lots of improvement.
check out this link for better understanding - https://github.com/AmolAmrit/Escrima_kernel_xiaomi_msm8956

**Comment by uditkarode** [comment]
I use AnyKernel3 already, there's no need to merge it into the tree
plus, how does it enhance performance? It just lets you unpack the boot image, place the kernel, and repack it, and its work is done.
