### ISSUE TITLE
How to compile redmi Note 7 pro kernel

### ISSUE THREAD

**Issue by Z3wn** [uditkarode/crimson#2]
I can't find any defconfig to compile kernel for my redmi Note 7 pro

**Comment by iamsaalim** [comment]
where did you even checked it ,

**Comment by uditkarode** [comment]
to compile a kernel you have to sacrifice your soul to satan.

**Comment by Z3wn** [comment]
@uditkarode  I mean, How can I build this kernel?

**Comment by iamsaalim** [comment]
tell what issues you are getting
